/** SEARCH-GROUPED-VEHICLE-POPUP-01 */

export const SEARCH_SUGGEST_GROUP_LIMIT = 3;
export const SEARCH_SUGGEST_PRODUCTS_PER_GROUP = 2;
export const SEARCH_SUGGEST_PREVIEW_MAX_TOTAL = 6;

/** @deprecated use SEARCH_SUGGEST_GROUP_LIMIT */
export const SEARCH_SUGGEST_CATEGORY_BLOCK_LIMIT = SEARCH_SUGGEST_GROUP_LIMIT;
/** @deprecated use SEARCH_SUGGEST_PRODUCTS_PER_GROUP */
export const SEARCH_SUGGEST_PRODUCTS_PER_CATEGORY = SEARCH_SUGGEST_PRODUCTS_PER_GROUP;
